### ISSUE TITLE
Idea: allow multiple expect targets, and all of them must be satisfied

### ISSUE THREAD

**Issue by johndbro1** [paclabsnet/raygun#3]
```
      type: substring
      target: 
       - "allow":false'
       - target: 'fnord'

```

OR

```
expects:
  - substring: "allow":false'
  - substring: fnord

```
Not sure whether we can support both the single-element and multi-element options. Will need to experiment!
